# demo
> https://www.bilibili.com/video/BV1HW411X7SM?p=5

In [8]:
import torch
from torchvision import transforms,models,datasets
import matplotlib
from matplotlib import pyplot as plt
from matplotlib.pyplot import GridSpec
import numpy as np
import pandas as pd
import os, sys
import seaborn as sns
sns.set(style="ticks")

In [4]:
torch.__version__

'1.4.0'

### TF

In [2]:
import tensorflow as tf

In [10]:
hello = tf.constant('hello tommy')

d1 = tf.Variable(10,name='var')


In [13]:
sess = tf.Session()
sess.run(hello)
init = tf.global_variables_initializer()# 变量必须初始化
sess.run(init)
sess.run(d1)
sess.close()

In [15]:
init = tf.global_variables_initializer()
sess = tf.Session()
# with 可以不用close session
with sess:
    sess.run(init)
    print(sess.run(d1))

10


In [20]:
with tf.Session() as sess:
    print(sess.run(hello))

b'hello tommy'


### placehold

In [21]:
data1 = tf.placeholder(tf.float32)
data2 = tf.placeholder(tf.float32)
dataAdd = tf.add(data1,data2)
with tf.Session() as sess:
    print(sess.run(dataAdd,feed_dict ={data1:6,data2:2}))


8.0


In [29]:
data1 = tf.constant([ [6,6] ])
data2 = tf.constant([ [2],
                      [2] ])

data3 = tf.constant([ [3,3] ])

data4 = tf.constant([ [1,2],
                      [3,4],
                      [5,6]])

print(data4.shape)
with tf.Session() as sess:
    print(sess.run(data4))
    print(sess.run(data4[0]))
    print(sess.run(data4[:,0]))
    print(sess.run(data4[0,1]))

(3, 2)
[[1 2]
 [3 4]
 [5 6]]
[1 2]
[1 3 5]
2


In [31]:
matMul = tf.matmul(data1,data2)
matMul2 = tf.multiply(data1,data2)

matAdd = tf.add(data1,data3)
with tf.Session() as sess:
    print(sess.run(matMul))
    print(sess.run(matAdd))
    print(sess.run(matMul2))


[[24]]
[[9 9]]
[[12 12]
 [12 12]]


### Iamge read

In [2]:
import cv2

In [2]:
img = cv2.imread("lena.jpg",1)

In [3]:
cv2.imshow('img',img)
cv2.waitKey(0)

27

### iamge write

In [9]:
img = cv2.imread("lena.jpg",0)
cv2.imwrite('gray.jpg',img,[cv2.IMWRITE_JPEG_QUALITY,50]) # 图片质量 0-100 有损

True

In [10]:
img = cv2.imread("lena.jpg",0)
cv2.imwrite('gray.png',img,[cv2.IMWRITE_PNG_COMPRESSION,9]) # 压缩比 0-9 无损

True

In [15]:
img = cv2.imread("lena.jpg",1)
(b,g,r)= img[100,100]
print(b,g,r)
for i in range(1,100):
    img[10+i,100] = (255,0,0)

cv2.imshow('imge',img)
cv2.waitKey(0)

87 74 182


27